import os
import yaml
import datetime
import json
import re
import pandas as pd
from fredapi import Fred
from google import genai
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# ==========================================
# 1. 環境設定
# ==========================================
FRED_API_KEY = os.getenv("FRED_API_KEY")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
CONFIG_PATH = "config/indicators.yml"
FONT_PATH = "ipaexg.ttf"
OUTPUT_IMAGE = "output_sns.png"
OUTPUT_MD = "analysis.md"

# クライアント初期化
client = genai.Client(api_key=GOOGLE_API_KEY)

def load_config():
    with open(CONFIG_PATH, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

def get_fred_data(indicators):
    fred = Fred(api_key=FRED_API_KEY)
    data_results = {}
    latest_values = {}
    for item in indicators:
        series_id = item['id']
        label = item['label']
        series = fred.get_series(series_id)
        data_results[label] = series.tail(12)
        latest_values[label] = series.iloc[-1]
    return data_results, latest_values

# ==========================================
# 3. AI分析ロジック (2026安定版)
# ==========================================
def analyze_with_gemini(latest_values):
    prompt = f"""
    あなたは経済アナリストです。以下のデータを分析し、JSON形式で回答してください。
    【データ】
    - NFP: {latest_values.get('非農業部門雇用者数 (NFP)', 'N/A')}
    - DXY: {latest_values.get('ドルインデックス', 'N/A')}
    - CPI: {latest_values.get('消費者物価指数 (CPI)', 'N/A')}

    【出力ルール】
    以下のキーを持つ純粋なJSONのみを返してください。
    {{ "summary": "...", "nfp_insight": "...", "dxy_trend": "...", "dxy_insight": "...", "cpi_insight": "...", "overall_outlook": "..." }}
    """
    
    # モデル名を 'gemini-1.5-flash' に固定し、SDKの自動解決に任せます
    response = client.models.generate_content(
        model='gemini-1.5-flash', 
        contents=prompt
    )
    
    # JSONパースの強化
    text = response.text
    json_match = re.search(r'\{.*\}', text, re.DOTALL)
    if json_match:
        return json.loads(json_match.group())
    else:
        raise ValueError(f"Gemini出力がJSONではありません: {text}")

# ==========================================
# 4. レポート生成
# ==========================================
def generate_professional_markdown(analysis, latest_values):
    today = datetime.date.today().strftime("%Y/%m/%d")
    return f"""# 【Weekly Macro Insight】経済 Macro NOTE (KURURUGI)
📅 *作成日: {today}*

---
## 📈 エグゼクティブ・サマリー
> {analysis.get('summary')}

## 🔍 指標別分析
### 1. 非農業部門雇用者数 (NFP)
* **Fact:** {latest_values.get('非農業部門雇用者数 (NFP)')}
* **Insight:** {analysis.get('nfp_insight')}

### 2. ドルインデックス (DXY)
| 指標 | 現在値 | トレンド |
| :--- | :--- | :--- |
| **DXY** | {latest_values.get('ドルインデックス')} | {analysis.get('dxy_trend')} |

### 3. 消費者物価指数 (CPI)
* **注目:** {analysis.get('cpi_insight')}

## 💡 総括
{analysis.get('overall_outlook')}

---
**Generated by KURURUGI Macro System**
"""

def create_sns_image(data_results, config):
    plt.style.use('dark_background')
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    prop = fm.FontProperties(fname=FONT_PATH)
    target_labels = config.get('target_labels', list(data_results.keys()))
    for i, label in enumerate(target_labels[:3]):
        ax = axes[i]
        df = data_results[label]
        ax.plot(df.index, df.values, color='#00ffcc', linewidth=2)
        ax.set_title(label, fontproperties=prop)
    plt.tight_layout()
    plt.savefig(OUTPUT_IMAGE)

def main():
    print("🚀 Running KURURUGI Macro System...")
    config = load_config()
    data, latest = get_fred_data(config['indicators'])
    
    print("🧠 Analyzing with Gemini...")
    try:
        analysis_json = analyze_with_gemini(latest)
        final_md = generate_professional_markdown(analysis_json, latest)
        with open(OUTPUT_MD, "w", encoding="utf-8") as f:
            f.write(final_md)
        create_sns_image(data, config)
        print("✅ All processes completed successfully!")
    except Exception as e:
        print(f"❌ Error: {e}")
        exit(1)

if __name__ == "__main__":
    main()